use crate::types::{DataType, MemoryRegion, RegisterDef};

/// Memory regions to read from the battery
pub const DATA_MATRIX: &[MemoryRegion] = &[
    MemoryRegion { address_high: 0x00, address_low: 0x00, length: 0x02 },
    MemoryRegion { address_high: 0x00, address_low: 0x02, length: 0x02 },
    MemoryRegion { address_high: 0x00, address_low: 0x04, length: 0x05 },
    MemoryRegion { address_high: 0x00, address_low: 0x0D, length: 0x04 },
    MemoryRegion { address_high: 0x00, address_low: 0x11, length: 0x04 },
    MemoryRegion { address_high: 0x00, address_low: 0x15, length: 0x04 },
    MemoryRegion { address_high: 0x00, address_low: 0x19, length: 0x04 },
    MemoryRegion { address_high: 0x00, address_low: 0x23, length: 0x14 },
    MemoryRegion { address_high: 0x00, address_low: 0x37, length: 0x04 },
    MemoryRegion { address_high: 0x00, address_low: 0x69, length: 0x02 },
    MemoryRegion { address_high: 0x00, address_low: 0x7B, length: 0x01 },
    MemoryRegion { address_high: 0x40, address_low: 0x00, length: 0x04 },
    MemoryRegion { address_high: 0x40, address_low: 0x0A, length: 0x0A },
    MemoryRegion { address_high: 0x40, address_low: 0x14, length: 0x02 },
    MemoryRegion { address_high: 0x40, address_low: 0x16, length: 0x02 },
    MemoryRegion { address_high: 0x40, address_low: 0x19, length: 0x02 },
    MemoryRegion { address_high: 0x40, address_low: 0x1B, length: 0x02 },
    MemoryRegion { address_high: 0x40, address_low: 0x1D, length: 0x02 },
    MemoryRegion { address_high: 0x40, address_low: 0x1F, length: 0x02 },
    MemoryRegion { address_high: 0x60, address_low: 0x00, length: 0x02 },
    MemoryRegion { address_high: 0x60, address_low: 0x02, length: 0x02 },
    MemoryRegion { address_high: 0x60, address_low: 0x04, length: 0x04 },
    MemoryRegion { address_high: 0x60, address_low: 0x08, length: 0x04 },
    MemoryRegion { address_high: 0x60, address_low: 0x0C, length: 0x02 },
    MemoryRegion { address_high: 0x90, address_low: 0x00, length: 0x3A },
    MemoryRegion { address_high: 0x90, address_low: 0x3A, length: 0x3A },
    MemoryRegion { address_high: 0x90, address_low: 0x74, length: 0x3A },
    MemoryRegion { address_high: 0x90, address_low: 0xAE, length: 0x3A },
    MemoryRegion { address_high: 0x90, address_low: 0xE8, length: 0x3A },
    MemoryRegion { address_high: 0x91, address_low: 0x22, length: 0x30 },
    MemoryRegion { address_high: 0x91, address_low: 0x52, length: 0x00 },
    MemoryRegion { address_high: 0xA0, address_low: 0x00, length: 0x06 },
];

/// Register definitions for data interpretation
pub fn create_data_id() -> Vec<RegisterDef> {
    vec![
        RegisterDef { address: 0x0000, length: 2, data_type: DataType::UInt, label: "Cell type".to_string() },
        RegisterDef { address: 0x0002, length: 2, data_type: DataType::UInt, label: "Unknown (always 0)".to_string() },
        RegisterDef { address: 0x0004, length: 5, data_type: DataType::SerialNumber, label: "Capacity & Serial number (?)".to_string() },
        RegisterDef { address: 0x000D, length: 4, data_type: DataType::UInt, label: "Unknown (4th code?)".to_string() },
        RegisterDef { address: 0x0011, length: 4, data_type: DataType::Date, label: "Manufacture date".to_string() },
        RegisterDef { address: 0x0015, length: 4, data_type: DataType::Date, label: "Date of first charge (Forge)".to_string() },
        RegisterDef { address: 0x0019, length: 4, data_type: DataType::Date, label: "Date of last charge (Forge)".to_string() },
        RegisterDef { address: 0x0023, length: 20, data_type: DataType::Ascii, label: "Note (ascii string)".to_string() },
        RegisterDef { address: 0x0037, length: 4, data_type: DataType::Date, label: "Current date".to_string() },
        RegisterDef { address: 0x0069, length: 2, data_type: DataType::UInt, label: "Unknown (always 2)".to_string() },
        RegisterDef { address: 0x007B, length: 1, data_type: DataType::UInt, label: "Unknown (always 0)".to_string() },
        RegisterDef { address: 0x4000, length: 4, data_type: DataType::UInt, label: "Unknown (Forge)".to_string() },
        RegisterDef { address: 0x400A, length: 10, data_type: DataType::CellVoltages, label: "Cell voltages (mV)".to_string() },
        RegisterDef { address: 0x4014, length: 2, data_type: DataType::AdcTemperature, label: "Temperature (C) (non-Forge)".to_string() },
        RegisterDef { address: 0x4016, length: 2, data_type: DataType::UInt, label: "Unknown (Forge)".to_string() },
        RegisterDef { address: 0x4019, length: 2, data_type: DataType::UInt, label: "Unknown (Forge)".to_string() },
        RegisterDef { address: 0x401B, length: 2, data_type: DataType::UInt, label: "Unknown (Forge)".to_string() },
        RegisterDef { address: 0x401D, length: 2, data_type: DataType::UInt, label: "Unknown (Forge)".to_string() },
        RegisterDef { address: 0x401F, length: 2, data_type: DataType::DecimalTemperature, label: "Temperature (C) (Forge)".to_string() },
        RegisterDef { address: 0x6000, length: 2, data_type: DataType::UInt, label: "Unknown (Forge)".to_string() },
        RegisterDef { address: 0x6002, length: 2, data_type: DataType::UInt, label: "Unknown (Forge)".to_string() },
        RegisterDef { address: 0x6004, length: 4, data_type: DataType::UInt, label: "Unknown (Forge)".to_string() },
        RegisterDef { address: 0x6008, length: 4, data_type: DataType::UInt, label: "Unknown (Forge)".to_string() },
        RegisterDef { address: 0x600C, length: 2, data_type: DataType::UInt, label: "Unknown (Forge)".to_string() },
        RegisterDef { address: 0x9000, length: 4, data_type: DataType::Date, label: "Date of first charge (rounded)".to_string() },
        RegisterDef { address: 0x9004, length: 4, data_type: DataType::Date, label: "Date of last tool use (rounded)".to_string() },
        RegisterDef { address: 0x9008, length: 4, data_type: DataType::Date, label: "Date of last charge (rounded)".to_string() },
        RegisterDef { address: 0x900C, length: 4, data_type: DataType::Date, label: "Unknown date (often zero)".to_string() },
        RegisterDef { address: 0x9010, length: 2, data_type: DataType::UInt, label: "Days since first charge".to_string() },
        RegisterDef { address: 0x9012, length: 4, data_type: DataType::UInt, label: "Total discharge (amp-sec)".to_string() },
        RegisterDef { address: 0x9016, length: 4, data_type: DataType::UInt, label: "Total discharge (watt-sec or joules)".to_string() },
        RegisterDef { address: 0x901A, length: 4, data_type: DataType::UInt, label: "Total charge count".to_string() },
        RegisterDef { address: 0x901E, length: 2, data_type: DataType::UInt, label: "Dumb charge count (J2>7.1V for >=0.48s)".to_string() },
        RegisterDef { address: 0x9020, length: 2, data_type: DataType::UInt, label: "Redlink (UART) charge count".to_string() },
        RegisterDef { address: 0x9022, length: 2, data_type: DataType::UInt, label: "Completed charge count (?)".to_string() },
        RegisterDef { address: 0x9024, length: 4, data_type: DataType::Duration, label: "Total charging time (HH:MM:SS)".to_string() },
        RegisterDef { address: 0x9028, length: 4, data_type: DataType::Duration, label: "Time on charger whilst full (HH:MM:SS)".to_string() },
        RegisterDef { address: 0x902C, length: 2, data_type: DataType::UInt, label: "Unknown (another low-voltage charge counter?)".to_string() },
        RegisterDef { address: 0x902E, length: 2, data_type: DataType::UInt, label: "Charge started with a cell < 2.5V".to_string() },
        RegisterDef { address: 0x9030, length: 2, data_type: DataType::UInt, label: "Discharge to empty".to_string() },
        RegisterDef { address: 0x9032, length: 2, data_type: DataType::UInt, label: "Num. overheat on tool (must be > 10A)".to_string() },
        RegisterDef { address: 0x9034, length: 2, data_type: DataType::UInt, label: "Overcurrent?".to_string() },
        RegisterDef { address: 0x9036, length: 2, data_type: DataType::UInt, label: "Low voltage events)".to_string() },
        RegisterDef { address: 0x9038, length: 2, data_type: DataType::UInt, label: "Low-voltage bounce? (4 flashing LEDs)".to_string() },
        // Discharge histogram entries (10-20A through 200A+)
        RegisterDef { address: 0x903A, length: 2, data_type: DataType::UInt, label: "Discharge @ 10-20A (seconds)".to_string() },
        RegisterDef { address: 0x903C, length: 2, data_type: DataType::UInt, label: "          @ 20-30A (could be watts)".to_string() },
        RegisterDef { address: 0x903E, length: 2, data_type: DataType::UInt, label: "          @ 30-40A      ".to_string() },
        RegisterDef { address: 0x9040, length: 2, data_type: DataType::UInt, label: "          @ 40-50A      ".to_string() },
        RegisterDef { address: 0x9042, length: 2, data_type: DataType::UInt, label: "          @ 50-60A      ".to_string() },
        RegisterDef { address: 0x9044, length: 2, data_type: DataType::UInt, label: "          @ 60-70A      ".to_string() },
        RegisterDef { address: 0x9046, length: 2, data_type: DataType::UInt, label: "          @ 70-80A      ".to_string() },
        RegisterDef { address: 0x9048, length: 2, data_type: DataType::UInt, label: "          @ 80-90A      ".to_string() },
        RegisterDef { address: 0x904A, length: 2, data_type: DataType::UInt, label: "          @ 90-100A     ".to_string() },
        RegisterDef { address: 0x904C, length: 2, data_type: DataType::UInt, label: "          @ 100-110A    ".to_string() },
        RegisterDef { address: 0x904E, length: 2, data_type: DataType::UInt, label: "          @ 110-120A    ".to_string() },
        RegisterDef { address: 0x9050, length: 2, data_type: DataType::UInt, label: "          @ 120-130A    ".to_string() },
        RegisterDef { address: 0x9052, length: 2, data_type: DataType::UInt, label: "          @ 130-140A    ".to_string() },
        RegisterDef { address: 0x9054, length: 2, data_type: DataType::UInt, label: "          @ 140-150A    ".to_string() },
        RegisterDef { address: 0x9056, length: 2, data_type: DataType::UInt, label: "          @ 150-160A    ".to_string() },
        RegisterDef { address: 0x9058, length: 2, data_type: DataType::UInt, label: "          @ 160-170A    ".to_string() },
        RegisterDef { address: 0x905A, length: 2, data_type: DataType::UInt, label: "          @ 170-180A    ".to_string() },
        RegisterDef { address: 0x905C, length: 2, data_type: DataType::UInt, label: "          @ 180-190A    ".to_string() },
        RegisterDef { address: 0x905E, length: 2, data_type: DataType::UInt, label: "          @ 190-200A    ".to_string() },
        RegisterDef { address: 0x9060, length: 2, data_type: DataType::UInt, label: "          @ 200-210A    ".to_string() },
        RegisterDef { address: 0x9062, length: 2, data_type: DataType::UInt, label: "Discharge @ 5-10A (seconds)".to_string() },
        // Second set of discharge histogram (10-15A through 200A+)
        RegisterDef { address: 0x9064, length: 2, data_type: DataType::UInt, label: "          @ 10-15A (could be watts)".to_string() },
        RegisterDef { address: 0x9066, length: 2, data_type: DataType::UInt, label: "          @ 15-20A (histo not well understood yet)".to_string() },
        RegisterDef { address: 0x9068, length: 2, data_type: DataType::UInt, label: "          @ 20-25A      ".to_string() },
        RegisterDef { address: 0x906A, length: 2, data_type: DataType::UInt, label: "          @ 25-30A      ".to_string() },
        RegisterDef { address: 0x906C, length: 2, data_type: DataType::UInt, label: "          @ 30-35A      ".to_string() },
        RegisterDef { address: 0x906E, length: 2, data_type: DataType::UInt, label: "          @ 35-40A      ".to_string() },
        RegisterDef { address: 0x9070, length: 2, data_type: DataType::UInt, label: "          @ 40-45A      ".to_string() },
        RegisterDef { address: 0x9072, length: 2, data_type: DataType::UInt, label: "          @ 45-50A      ".to_string() },
        RegisterDef { address: 0x9074, length: 2, data_type: DataType::UInt, label: "          @ 50-55A      ".to_string() },
        RegisterDef { address: 0x9076, length: 2, data_type: DataType::UInt, label: "          @ 55-60A      ".to_string() },
        RegisterDef { address: 0x9078, length: 2, data_type: DataType::UInt, label: "          @ 60-65A      ".to_string() },
        RegisterDef { address: 0x907A, length: 2, data_type: DataType::UInt, label: "          @ 65-70A      ".to_string() },
        RegisterDef { address: 0x907C, length: 2, data_type: DataType::UInt, label: "          @ 70-65A      ".to_string() },
        RegisterDef { address: 0x907E, length: 2, data_type: DataType::UInt, label: "          @ 75-80A      ".to_string() },
        RegisterDef { address: 0x9080, length: 2, data_type: DataType::UInt, label: "          @ 80-85A      ".to_string() },
        RegisterDef { address: 0x9082, length: 2, data_type: DataType::UInt, label: "          @ 85-90A      ".to_string() },
        RegisterDef { address: 0x9084, length: 2, data_type: DataType::UInt, label: "          @ 90-95A      ".to_string() },
        RegisterDef { address: 0x9086, length: 2, data_type: DataType::UInt, label: "          @ 95-100A     ".to_string() },
        RegisterDef { address: 0x9088, length: 2, data_type: DataType::UInt, label: "          @ 100-105A    ".to_string() },
        RegisterDef { address: 0x908A, length: 2, data_type: DataType::UInt, label: "          @ 105-110A    ".to_string() },
        RegisterDef { address: 0x908C, length: 2, data_type: DataType::UInt, label: "          @ 110-115A    ".to_string() },
        RegisterDef { address: 0x908E, length: 2, data_type: DataType::UInt, label: "          @ 115-120A    ".to_string() },
        RegisterDef { address: 0x9090, length: 2, data_type: DataType::UInt, label: "          @ 120-125A    ".to_string() },
        RegisterDef { address: 0x9092, length: 2, data_type: DataType::UInt, label: "          @ 125-130A    ".to_string() },
        RegisterDef { address: 0x9094, length: 2, data_type: DataType::UInt, label: "          @ 130-135A    ".to_string() },
        RegisterDef { address: 0x9096, length: 2, data_type: DataType::UInt, label: "          @ 135-140A    ".to_string() },
        RegisterDef { address: 0x9098, length: 2, data_type: DataType::UInt, label: "          @ 140-145A    ".to_string() },
        RegisterDef { address: 0x909A, length: 2, data_type: DataType::UInt, label: "          @ 145-150A    ".to_string() },
        RegisterDef { address: 0x909C, length: 2, data_type: DataType::UInt, label: "          @ 150-155A    ".to_string() },
        RegisterDef { address: 0x909E, length: 2, data_type: DataType::UInt, label: "          @ 155-160A    ".to_string() },
        RegisterDef { address: 0x90A0, length: 2, data_type: DataType::UInt, label: "          @ 160-165A    ".to_string() },
        RegisterDef { address: 0x90A2, length: 2, data_type: DataType::UInt, label: "          @ 165-170A    ".to_string() },
        RegisterDef { address: 0x90A4, length: 2, data_type: DataType::UInt, label: "          @ 170-175A    ".to_string() },
        RegisterDef { address: 0x90A6, length: 2, data_type: DataType::UInt, label: "          @ 175-180A    ".to_string() },
        RegisterDef { address: 0x90A8, length: 2, data_type: DataType::UInt, label: "          @ 180-185A    ".to_string() },
        RegisterDef { address: 0x90AA, length: 2, data_type: DataType::UInt, label: "          @ 185-190A    ".to_string() },
        RegisterDef { address: 0x90AC, length: 2, data_type: DataType::UInt, label: "          @ 190-195A    ".to_string() },
        RegisterDef { address: 0x90AE, length: 2, data_type: DataType::UInt, label: "          @ 195-200A    ".to_string() },
        RegisterDef { address: 0x90B0, length: 2, data_type: DataType::UInt, label: "          @ 200A+       ".to_string() },
        // Charge voltage ranges
        RegisterDef { address: 0x90B2, length: 2, data_type: DataType::UInt, label: "Charge started < 17V".to_string() },
        RegisterDef { address: 0x90B4, length: 2, data_type: DataType::UInt, label: "Charge started 17-18V".to_string() },
        RegisterDef { address: 0x90B6, length: 2, data_type: DataType::UInt, label: "Charge started 18-19V".to_string() },
        RegisterDef { address: 0x90B8, length: 2, data_type: DataType::UInt, label: "Charge started 19-20V".to_string() },
        RegisterDef { address: 0x90BA, length: 2, data_type: DataType::UInt, label: "Charge started 20V+".to_string() },
        RegisterDef { address: 0x90BC, length: 2, data_type: DataType::UInt, label: "Charge ended < 17V".to_string() },
        RegisterDef { address: 0x90BE, length: 2, data_type: DataType::UInt, label: "Charge ended 17-18V".to_string() },
        RegisterDef { address: 0x90C0, length: 2, data_type: DataType::UInt, label: "Charge ended 18-19V".to_string() },
        RegisterDef { address: 0x90C2, length: 2, data_type: DataType::UInt, label: "Charge ended 19-20V".to_string() },
        RegisterDef { address: 0x90C4, length: 2, data_type: DataType::UInt, label: "Charge ended 20V+".to_string() },
        // Temperature ranges for charging
        RegisterDef { address: 0x90C6, length: 2, data_type: DataType::UInt, label: "Charge start temp -30C to -20C".to_string() },
        RegisterDef { address: 0x90C8, length: 2, data_type: DataType::UInt, label: "Charge start temp -20C to -10C".to_string() },
        RegisterDef { address: 0x90CA, length: 2, data_type: DataType::UInt, label: "Charge start temp -10C to 0C".to_string() },
        RegisterDef { address: 0x90CC, length: 2, data_type: DataType::UInt, label: "Charge start temp 0C to +10C".to_string() },
        RegisterDef { address: 0x90CE, length: 2, data_type: DataType::UInt, label: "Charge start temp +10C to +20C".to_string() },
        RegisterDef { address: 0x90D0, length: 2, data_type: DataType::UInt, label: "Charge start temp +20C to +30C".to_string() },
        RegisterDef { address: 0x90D2, length: 2, data_type: DataType::UInt, label: "Charge start temp +30C to +40C".to_string() },
        RegisterDef { address: 0x90D4, length: 2, data_type: DataType::UInt, label: "Charge start temp +40C to +50C".to_string() },
        RegisterDef { address: 0x90D6, length: 2, data_type: DataType::UInt, label: "Charge start temp +50C to +60C".to_string() },
        RegisterDef { address: 0x90D8, length: 2, data_type: DataType::UInt, label: "Charge start temp +60C to +70C".to_string() },
        RegisterDef { address: 0x90DA, length: 2, data_type: DataType::UInt, label: "Charge start temp +70C to +80C".to_string() },
        RegisterDef { address: 0x90DC, length: 2, data_type: DataType::UInt, label: "Charge start temp +80C and over".to_string() },
        RegisterDef { address: 0x90DE, length: 2, data_type: DataType::UInt, label: "Charge end temp -30C to -20C".to_string() },
        RegisterDef { address: 0x90E0, length: 2, data_type: DataType::UInt, label: "Charge end temp -20C to -10C".to_string() },
        RegisterDef { address: 0x90E2, length: 2, data_type: DataType::UInt, label: "Charge end temp -10C to 0C".to_string() },
        RegisterDef { address: 0x90E4, length: 2, data_type: DataType::UInt, label: "Charge end temp 0C to +10C".to_string() },
        RegisterDef { address: 0x90E6, length: 2, data_type: DataType::UInt, label: "Charge end temp +10C to +20C".to_string() },
        RegisterDef { address: 0x90E8, length: 2, data_type: DataType::UInt, label: "Charge end temp +30C to +30C".to_string() },
        RegisterDef { address: 0x90EA, length: 2, data_type: DataType::UInt, label: "Charge end temp +30C to +40C".to_string() },
        RegisterDef { address: 0x90EC, length: 2, data_type: DataType::UInt, label: "Charge end temp +40C to +50C".to_string() },
        RegisterDef { address: 0x90EE, length: 2, data_type: DataType::UInt, label: "Charge end temp +50C to +60C".to_string() },
        RegisterDef { address: 0x90F0, length: 2, data_type: DataType::UInt, label: "Charge end temp +60C to +70C".to_string() },
        RegisterDef { address: 0x90F2, length: 2, data_type: DataType::UInt, label: "Charge end temp +70C to +80C".to_string() },
        RegisterDef { address: 0x90F4, length: 2, data_type: DataType::UInt, label: "Charge end temp +80C and over".to_string() },
        // Charge time histograms
        RegisterDef { address: 0x90F6, length: 2, data_type: DataType::UInt, label: "Dumb charge time (00:00-14:33)".to_string() },
        RegisterDef { address: 0x90F8, length: 2, data_type: DataType::UInt, label: "Dumb charge time (14:34-29:07)".to_string() },
        RegisterDef { address: 0x90FA, length: 2, data_type: DataType::UInt, label: "Dumb charge time (29:08-43:41)".to_string() },
        RegisterDef { address: 0x90FC, length: 2, data_type: DataType::UInt, label: "Dumb charge time (43:42-58:15)".to_string() },
        RegisterDef { address: 0x90FE, length: 2, data_type: DataType::UInt, label: "Dumb charge time (58:16-1:12:49)".to_string() },
        RegisterDef { address: 0x9100, length: 2, data_type: DataType::UInt, label: "Dumb charge time (1:12:50-1:27:23)".to_string() },
        RegisterDef { address: 0x9102, length: 2, data_type: DataType::UInt, label: "Dumb charge time (1:27:24-1:41:57)".to_string() },
        RegisterDef { address: 0x9104, length: 2, data_type: DataType::UInt, label: "Dumb charge time (1:41:58-1:56:31)".to_string() },
        RegisterDef { address: 0x9106, length: 2, data_type: DataType::UInt, label: "Dumb charge time (1:56:32-2:11:05)".to_string() },
        RegisterDef { address: 0x9108, length: 2, data_type: DataType::UInt, label: "Dumb charge time (2:11:06-2:25:39)".to_string() },
        RegisterDef { address: 0x910A, length: 2, data_type: DataType::UInt, label: "Dumb charge time (2:25:40-2:40:13)".to_string() },
        RegisterDef { address: 0x910C, length: 2, data_type: DataType::UInt, label: "Dumb charge time (2:40:14-2:54:47)".to_string() },
        RegisterDef { address: 0x910E, length: 2, data_type: DataType::UInt, label: "Dumb charge time (2:54:48-3:09:21)".to_string() },
        RegisterDef { address: 0x9110, length: 2, data_type: DataType::UInt, label: "Dumb charge time (3:09:22-3:23:55)".to_string() },
        RegisterDef { address: 0x9112, length: 2, data_type: DataType::UInt, label: "Redlink charge time (00:00-17:03)".to_string() },
        RegisterDef { address: 0x9114, length: 2, data_type: DataType::UInt, label: "Redlink charge time (17:04-34:07)".to_string() },
        RegisterDef { address: 0x9116, length: 2, data_type: DataType::UInt, label: "Redlink charge time (34:08-51:11)".to_string() },
        RegisterDef { address: 0x9118, length: 2, data_type: DataType::UInt, label: "Redlink charge time (51:12-1:08:15)".to_string() },
        RegisterDef { address: 0x911A, length: 2, data_type: DataType::UInt, label: "Redlink charge time (1:08:16-1:25:19)".to_string() },
        RegisterDef { address: 0x911C, length: 2, data_type: DataType::UInt, label: "Redlink charge time (1:25:20-1:42:23)".to_string() },
        RegisterDef { address: 0x911E, length: 2, data_type: DataType::UInt, label: "Redlink charge time (1:42:24-1:59:27)".to_string() },
        RegisterDef { address: 0x9120, length: 2, data_type: DataType::UInt, label: "Redlink charge time (1:59:28-2:16:31)".to_string() },
        RegisterDef { address: 0x9122, length: 2, data_type: DataType::UInt, label: "Redlink charge time (2:16:32-2:33:35)".to_string() },
        RegisterDef { address: 0x9124, length: 2, data_type: DataType::UInt, label: "Redlink charge time (2:33:36-2:50:39)".to_string() },
        RegisterDef { address: 0x9126, length: 2, data_type: DataType::UInt, label: "Redlink charge time (2:50:40-3:07:43)".to_string() },
        RegisterDef { address: 0x9128, length: 2, data_type: DataType::UInt, label: "Redlink charge time (3:07:44-3:24:47)".to_string() },
        RegisterDef { address: 0x912A, length: 2, data_type: DataType::UInt, label: "Redlink charge time (3:24:48-3:41:51)".to_string() },
        RegisterDef { address: 0x912C, length: 2, data_type: DataType::UInt, label: "Redlink charge time (3:41:52-3:58:55)".to_string() },
        RegisterDef { address: 0x912E, length: 2, data_type: DataType::UInt, label: "Completed charge (?)".to_string() },
        // Final unknown registers
        RegisterDef { address: 0x9130, length: 2, data_type: DataType::UInt, label: "Unknown".to_string() },
        RegisterDef { address: 0x9132, length: 2, data_type: DataType::UInt, label: "Unknown".to_string() },
        RegisterDef { address: 0x9134, length: 2, data_type: DataType::UInt, label: "Unknown".to_string() },
        RegisterDef { address: 0x9136, length: 2, data_type: DataType::UInt, label: "Unknown".to_string() },
        RegisterDef { address: 0x9138, length: 2, data_type: DataType::UInt, label: "Unknown".to_string() },
        RegisterDef { address: 0x913A, length: 2, data_type: DataType::UInt, label: "Unknown".to_string() },
        RegisterDef { address: 0x913C, length: 2, data_type: DataType::UInt, label: "Unknown".to_string() },
        RegisterDef { address: 0x913E, length: 2, data_type: DataType::UInt, label: "Unknown".to_string() },
        RegisterDef { address: 0x9140, length: 2, data_type: DataType::UInt, label: "Unknown".to_string() },
        RegisterDef { address: 0x9142, length: 2, data_type: DataType::UInt, label: "Unknown histogram (temperature?)".to_string() },
        RegisterDef { address: 0x9144, length: 2, data_type: DataType::UInt, label: "Unknown histogram".to_string() },
        RegisterDef { address: 0x9146, length: 2, data_type: DataType::UInt, label: "Unknown histogram".to_string() },
        RegisterDef { address: 0x9148, length: 2, data_type: DataType::UInt, label: "Unknown histogram".to_string() },
        RegisterDef { address: 0x914A, length: 2, data_type: DataType::UInt, label: "Unknown histogram".to_string() },
        RegisterDef { address: 0x914C, length: 2, data_type: DataType::UInt, label: "Unknown histogram".to_string() },
        RegisterDef { address: 0x914E, length: 2, data_type: DataType::UInt, label: "Unknown histogram".to_string() },
        RegisterDef { address: 0x9150, length: 2, data_type: DataType::UInt, label: "Unknown histogram".to_string() },
    ]
}